Dev 99 103 api refactor
pepkit/pipestat pull request #108
Opened 2023-10-30 16:07 UTC by donaldcampbelljr

Adds `select_records`, `retrieve_one`, `retrieve_many ` interface, cursor_pagination for DBBackend.

Also refactored to store all configuration attributes in `psm.cfg`.

Changed magic functions, `__setitem__ `and `__getitem__`, to act as a wrapper for `report` and `retrieve` respectively.

Address #99 and #103

2023-10-30 19:53 UTC, khoroshevskyi requested changes
Looks good, few changes needed

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/backends/abstract.py
> +) -> List[Any]:
```suggestion
    self,
    columns: Optional[List[str]] = None,
    filter_conditions: Optional[List[Dict[str, Any]]] = None,
    limit: Optional[int] = 1000,
    cursor: Optional[int] = None,
    bool_operator: Optional[str] = "AND",
) -> Dict[str, Any]:
```

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/backends/db_backend/dbbackend.py
> +        :param list[tuple(str,str,str)] [(key,operator,value)] filter_conditions: e.g. [("id", "eq", 1)], operator list:
```suggestion
        :param list[dict]  filter_conditions: e.g. [{"key": ["id"], "operator": "eq", "value": 1)], operator list:
```

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        # self[RECORD_IDENTIFIER] = record_identifier
Can you please clean this. to many comments are. And probably noone will use them

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        # This is a wrapper for the retrieve function:
I like It!

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        result = self.report(record_identifier=key, values=value)
I like it too!

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
>      def __delitem__(self, key):
you can call `pipestat.remove` in this magic method

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        filter_conditions: Optional[List[Tuple[str, str, Union[str, List[str]]]]] = None,
```suggestion
        filter_conditions: Optional[List[Dict[str, Any]]] = None,
```

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        returns list of records
add ":param record_identifiers ..."

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +
```suggestion
        filter = {
            "key": "record_identifier",
            "operator": "in",
            "value": record_identifiers,
        }

        return self.select_records(filter_conditions=[filter])

```

2023-10-30 19:53 UTC, khoroshevskyi commented on pipestat/pipestat.py
> +        r_id = record_identifier or self.cfg[RECORD_IDENTIFIER]
Nice!

2023-10-30 19:53 UTC, khoroshevskyi commented on tests/data/sample_output_schema.yaml
> +#            type: integer
```suggestion
```

2023-10-31 02:36 UTC, khoroshevskyi requested changes
One critical change needed

2023-10-31 02:36 UTC, khoroshevskyi commented on pipestat/backends/db_backend/db_helpers.py
Delete dynamic filter, as it is replaced by selection filter

2023-10-31 10:46 UTC, donaldcampbelljr commented on pipestat/backends/db_backend/db_helpers.py
I left _all_ of the old functions in pipestat for now until it was decided if we want to keep them for backwards compat or not. Dynamic filter is required for the original `select` function.

2023-10-31 16:42 UTC, khoroshevskyi approved these changes
LGTM

2023-10-31 18:44 UTC, donaldcampbelljr commented
- [ ] remove unused funcs (e.g. select_txt)
- [ ] make wrapper around list_recent_results (but use `select_records` backend)
- [ ] use select_records for filebackend as well.

2023-11-01 15:34 UTC, donaldcampbelljr commented
I added the select_records function to the filebackend, but it is missing the ability to filter by result_identifiers (columns). Currently it only retrieves the entire record.

2023-11-02 17:09 UTC, donaldcampbelljr commented
- [ ] get_one_record, get_records, retrieve still exist on the backends, we should be able to remove them and simply use `select_records`.

2023-11-03 23:05 UTC, donaldcampbelljr commented
removing retrieve is still a work in progress. also need to decide where to place `RecordNotFoundError` since it lists in Retrieve but not select_records.

2023-11-04 13:04 UTC, donaldcampbelljr commented
retrieve is now completely removed.

I attempted to re-implement RecordNotFound for retrieve_one and retrieve_many but its not quite behaving as expected.

2023-11-06 16:12 UTC, merged